### ISSUE TITLE
Something that allow not to put all .js files to index

### ISSUE THREAD

**Issue by matjanos** [przemkow/ApartMates#9]
Powinniśmy znaleźć coś co buduje drzewo zależności plików w projekcie i nie wymaga żeby dodawać wszyskie .js'y do pliku html.

**Comment by przemkow** [comment]
Można by do tego użyć 2 rzeczy, browserify lub require js. Projekt skonfigurowałem pod browserify ale problem jest taki że sporo sie tam teraz sypie , wydaje mi się że dałbym radę to zrobić ale nie widzę sensu marnowania na to teraz czasu skoro na cały projekt nie mamy go zbyt wiele. 
jak nauczymy się dobrze angulara to kolejny projekt można od razu postawić korzystając z narzędzi które automatycznie budują apke do folderu dist.
